name: Deploy docs

on:
  push:
    branches:
        - main

permissions:
    contents: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
          pip install -r requirements_dev.txt
          pip install -r requirements.txt
          pip list

    - name: Clean gh-pages
      run: |
        git fetch origin gh-pages || echo "No gh-pages branch yet"
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        git commit -m "Clean branch" || echo "Nothing to clean"
        git push origin gh-pages --force

    - name: Deploy docs
      run: |
        export PYTHONPATH=$(pwd)/src
        mkdocs gh-deploy --force
